# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Builds an appbundle and uploads it to the play store beta track"
  lane :beta do

    # build appbundle
    sh(
      "flutter",
      "build",
      "appbundle",
      "--flavor",
      "free",
      "-t",
      "lib/main_free.dart",
      "--bundle-sksl-path",
      "sksl.json"
    )

    upload_to_play_store(
      track: 'beta',
      aab: '../build/app/outputs/bundle/freeRelease/app-free-release.aab'
    )

  end
end
