name: CI

on: [ pull_request ]

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter packages pub run build_runner build
      - run: flutter analyze
      - run: flutter format . --set-exit-if-changed
      - run: flutter test
      - run: flutter build appbundle --flavor free --dart-define=flavor=free
