name: CI

on: [ pull_request ]

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build appbundle --flavor free --dart-define=flavor=free
